######################################################################
##
## Filename: Rechner.udo
## Created on: Thu Jul 09 08:30:32 W. Europe Summer Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
