######################################################################
##
## Filename: RCA_16.udo
## Created on: Tue Jun 23 10:54:48 W. Europe Summer Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
